### ISSUE TITLE
Ring tactic

### ISSUE THREAD

**Issue by ifarabella** [hhu-adam/NNG4#12]
When making some theorems of my own I encountered the following goal:
⊢ t + t + 1 + (s + s + 1) = t + s + 1 + (t + s + 1)
I expected the ring tactic to solve this but it appears that ring is missing from the repository.
Would it be possible to add functionality so that the ring tactic would solve this?

**Comment by abentkamp** [comment]
It's currently not possible to import Mathlib (which contains the `ring` tactic) from the NNG. The reason is that the NNG would like to use some modified versions of tactics different from Mathlib (e.g. a simplified version of `rw`).

Here is a game that uses Mathlib: https://github.com/hhu-adam/Robo. Maybe you can start from there?

Or you could copy the entire ring tactic from Mathlib.

**Comment by joneugster** [comment]
hey @ifarabella , I've been chatting with Kevin and I'm working today on the NNG, getting some tactics to work. Maybe we could chat on zulip to coordinate efforts

**Comment by kbuzzard** [comment]
FWIW I have a branch of NNG where this goal (and even  is being solved by my variant of `ac_rfl`, namely `simp only [add_assoc, add_left_comm, add_comm]`. But this trick won't scale to multiplication.

**Comment by joneugster** [comment]
Now, few weeks later, the NNG imports mathlib
